export const members = [
    { label: 'Nita', family: 'RSJ' },
    { label: 'Baby', family: 'RSJ' },
    { label: 'Rick', family: 'RSJ' },
    { label: 'Harold', family: 'RSJ' },
    { label: 'Jenn', family: 'RSJ' },
    { label: 'Grant', family: 'RSJ' },
    { label: 'Carl', family: 'RSJ' },
    { label: 'Jan', family: 'RSJ' },
    { label: 'Edwin', family: 'RSJ' },
    { label: 'Malou', family: 'RSJ' },
    { label: 'Rpee', family: 'RSJ' },
    { label: 'Travis', family: 'RSJ' },
    { label: 'Marwin', family: 'RSJ' },
    { label: 'Raffy', family: 'RSJ' },
    { label: 'Majo', family: 'RSJ' },
    { label: 'Ryan', family: 'RSJ' },
    { label: 'Luna', family: 'RSJ' },
    { label: 'Alonzo', family: 'RSJ' },
    { label: 'Sean', family: 'RSJ' },
    { label: 'Martina', family: 'RSJ' },
    { label: 'Rocco', family: 'RSJ' },
    { label: 'Zeny', family: 'RSJ' },
    { label: 'Hansel', family: 'RSJ' },
    { label: 'Hazel', family: 'RSJ' },
    { label: 'Mark Liriel', family: 'RSJ' },
    { label: 'Noah', family: 'RSJ' },
    { label: 'Zoe', family: 'RSJ' },
    { label: 'Sachi', family: 'RSJ' },
    { label: 'Frances', family: 'RSJ' },
    { label: 'Richard', family: 'RSJ' },
    { label: 'Vincent', family: 'RSJ' },
    { label: 'Charlize Kate', family: 'RSJ' },
    { label: 'Mark Haze', family: 'RSJ' },
    { label: 'Mark Crylle', family: 'RSJ' },
    { label: 'Cardale', family: 'RSJ' },
    { label: 'Yui', family: 'RSJ' },
    { label: 'Kratos', family: 'RSJ' },
    { label: 'Katrina', family: 'RSJ' },
    { label: 'Jamil', family: 'RSJ' },
    { label: 'Dennis', family: 'RSJ' },
    { label: 'Berna', family: 'RSJ' },
    { label: 'Felix', family: 'RSJ' },
    { label: 'Denise', family: 'RSJ' },
    { label: 'Anne', family: 'RSJ' },
    { label: 'Caelum', family: 'RSJ' },
    { label: 'Danny', family: 'RSJ' },
    { label: 'Dan Marlou', family: 'RSJ' },
    { label: 'Daene', family: 'RSJ' },
    { label: 'Resty', family: 'ESJ' },
    { label: 'Lita', family: 'ESJ' },
    { label: 'Peen', family: 'ESJ' },
    { label: 'Fidel', family: 'ESJ' },
    { label: 'Tessa', family: 'ESJ' },
    { label: 'Kaye', family: 'ESJ' },
    { label: 'TJ', family: 'ESJ' },
    { label: 'Gie', family: 'ESJ' },
    { label: 'Maeng', family: 'ESJ' },
    { label: 'Joelle', family: 'ESJ' },
    { label: 'Pam', family: 'ESJ' },
    { label: 'Clarita', family: 'CSJ' },
    { label: 'Santy', family: 'CSJ' },
    { label: 'Shirley', family: 'CSJ' },
    { label: 'Jodi', family: 'CSJ' },
    { label: 'Crispin', family: 'CSJ' },
    { label: 'Linda', family: 'CSJ' },
    { label: 'Crislyn', family: 'CSJ' },
    { label: 'Baba', family: 'CSJ' },
    { label: 'Renren', family: 'CSJ' },
    { label: 'Kulot', family: 'CSJ' },
    { label: 'Julie', family: 'CSJ' },
    { label: 'MC', family: 'CSJ' },
    { label: 'Ian', family: 'CSJ' },
    { label: 'Chy', family: 'CSJ' }
];
